### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by nk932714** [mevdschee/youtube-playlist-extractor#2]
Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in /home/public_html/playlist.php on line 12

Warning: file_get_contents(): Failed to enable crypto in /home/public_html/playlist.php on line 12

Warning: file_get_contents(https://www.youtube.com/playlist?list=PL2ntRZ1ySWBdliXelGAItjzTMxy2WQh0P): failed to open stream: operation failed in /home/public_html/playlist.php on line 12

**Comment by nk932714** [comment]
please check your channel.php too

**Comment by mevdschee** [comment]
Can you disable peer verification and see whether or not that works?

**Comment by nk932714** [comment]
Thanks this issue has been resolved.
